# Run starship
eval "$(starship init bash)"

# Add aliases
alias g="git"
alias c="code"
alias v="vim"
alias y="yarn"
alias d="docker"
alias dc="docker-compose"
alias lzd="lazydocker"

# Set VI mode
set -o vi

# Add completion for the g alias
__git_complete g __git_main

# Adding to path
export PATH=$PATH:/c/Users/FrancescoFerraioli/scripts
export PATH=$PATH:/c/Users/FrancescoFerraioli/scripts/wsl

# Save history
PROMPT_COMMAND="${PROMPT_COMMAND} && history -a"

z () {
	if [ -z $1 ]; then
		return;
	fi

	Z_BEST_MATCH=$(ls -1 | rg $1 | head -n 1)

	if [ ! -z $Z_BEST_MATCH ]; then
		cd $Z_BEST_MATCH
	fi
}

repos () {
	cd ~/source/repos
	z $1
}